on:
  push:
    branches:
      main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        env:
          USERNAME: ${{ secrets.USERNAME }}
          HOST: ${{ secrets.HOST }}
          KEY: ${{ secrets.SSH_KEY }}
          PORT: ${{ secrets.PORT }}
        with:
          source: '.'
          target: '/home/ubuntu/acm/'
